
CREATE TABLE ordenes (
id SERIAL PRIMARY KEY,
chofer VARCHAR(255),
fecha_llegada DATE,
orden_firma DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE fabricas (
id SERIAL PRIMARY KEY,
nombre TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE cierres (
id SERIAL PRIMARY KEY,
fecha_salida DATE,
numero_salidas TEXT,
numero_stock TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE salidas (
id SERIAL PRIMARY KEY,
fabrica TEXT,
fecha_salida DATE,
remitos TEXT,
aberturas TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email   VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

ALTER TABLE empleados ADD COLUMN user_id INTEGER REFERENCES users(id);

